### ISSUE TITLE
请问一下Sever端推流模块为什么我老是推流不成功呢，Client 一连接就断了

### ISSUE THREAD

**Issue by NothingDe** [itisyang/p2p-audio-and-video-transmission-system#1]

**Comment by NothingDe** [comment]
还有这个Client 里面的Key 是好像是你自己的我们都可以看到你们办公室。。

**Comment by itisyang** [comment]
这是测试key，如果过要正式使用需要购买TUTK的服务

**Comment by NothingDe** [comment]
已经购买了几个试用的，我用demo里面 RDT 模块发送文件都是可以的，但是推流Client 一连接就断了，麻烦帮忙看一下，我把音频模块全屏蔽了  这是我的Key  ELYU9X2WZDZW9M6GUHEJ
![image](https://user-images.githubusercontent.com/11494329/101300921-2bf78100-3872-11eb-95cc-2320846eee1d.png)

**Comment by NothingDe** [comment]
received cmd

Handle CMD: 0x300

IOTYPE_USER_IPCAM_AUDIOSTART, ch:0, avIndex:0 客户端已连接就提示这个

**Comment by itisyang** [comment]
如果购买了，直接用他们提供的demo就行了，我这个只是写着玩的，好多年了，记不得了

**Comment by NothingDe** [comment]
好的 谢谢了
